package me.jadenp.notmagic.RevisedClasses;

import net.md_5.bungee.api.ChatColor;
import org.bukkit.DyeColor;
import org.bukkit.Material;
import org.bukkit.NamespacedKey;
import org.bukkit.attribute.Attribute;
import org.bukkit.attribute.AttributeModifier;
import org.bukkit.block.banner.Pattern;
import org.bukkit.block.banner.PatternType;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BannerMeta;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.inventory.meta.PotionMeta;
import org.bukkit.material.MaterialData;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.potion.PotionType;
import org.checkerframework.checker.units.qual.A;

import java.awt.*;
import java.util.ArrayList;
import java.util.UUID;

public class Items {
    // stick bamboo amethyst blaze rod bone feather
    public ItemStack data(String s){
        if (s.equalsIgnoreCase("BasicWand")){
            ItemStack Item = new ItemStack(Material.BLAZE_ROD);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.GRAY + "Basic Wand");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Starting Point for Magic");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("MagicDust")){
            ItemStack Item = new ItemStack(Material.GLOWSTONE_DUST);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Magic Dust");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Essence of Magic");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBHeal")) {
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Heal Spell");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Secondary Spell:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Heals nearby players");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBBurn")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Burn Spell");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Main Spell:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Shoots flames at your enemy");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBStrength")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Strength Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Secondary Spell:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Gives strength to nearby players");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ProsaicWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(133, 121, 30)) + "Prosaic Wand");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Mediocre wand but better");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "than the basic wand");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBZap")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Zap Spell");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Secondary Spell:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Electrocutes an entity in front of");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "you, temporarily paralyzing them");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBBurst")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Burst:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Summons a gust of wind");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("MagicBlock")){
            ItemStack Item = new ItemStack(Material.GLOWSTONE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Magic Block");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "A more compact version of Magic Dust");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("CompressedMagicBlock")){
            ItemStack Item = new ItemStack(Material.GOLD_BLOCK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Compressed Magic Block");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "The purest form of Magic Dust");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBKineticElectrocute")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Kinetic Electrocute:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Summons a magic crystal to");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "electrocute nearby entities");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBThunderCloud")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Thunder Cloud:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Summons a thunder cloud to");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "follow a player");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("shadowRose")) {
            ItemStack Item = new ItemStack(Material.WITHER_ROSE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(org.bukkit.ChatColor.DARK_GRAY + "" + org.bukkit.ChatColor.BOLD + "Shadow Rose");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(org.bukkit.ChatColor.GRAY + "" + org.bukkit.ChatColor.ITALIC + "Dark Intentions");
            Meta.setLore(Lore);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DAMAGE_UNDEAD, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ShadowWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(71, 84, 92)) + "Shadow Wand");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Wand combined with the remains");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "of the Shadow Skeleton Boss");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBDarkSummoning")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Dark Summoning:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Summons a wither skeleton");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "to fight for you");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBSnipe2")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Snipe 2:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Shoots an arrow");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "that goes fast");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBDarkPoisoning")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Dark Poisoning:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Poison an Entity");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "in front of you");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBLocate")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Locate:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Locate the nearest player");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("EnhancedWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(27, 179, 120)) + "Enhanced Wand");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "A better crafted wand than");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "the Basic Wand");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBBurn2")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Burn 2:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Burn Entities with more POWER!");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBTeleport")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Teleport:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Teleport to where you are looking");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Note: You cannot teleport through blocks");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBShield")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Shield:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Create a shield to block all projectiles");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ParrotFamiliar")){
            ItemStack Item = new ItemStack(Material.PARROT_SPAWN_EGG, 1);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(235, 26, 75)) + "Parrot Familiar");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "Provides a sound cue when ");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "ancient debris or diamond ore");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "is nearby");
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("CatFamiliar")){
            ItemStack Item = new ItemStack(Material.CAT_SPAWN_EGG, 1);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(237, 173, 188)) + "Cat Familiar");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "Reduces owner's fall damage ");
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("DogFamiliar")){
            ItemStack Item = new ItemStack(Material.WOLF_SPAWN_EGG, 1);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(161, 217, 240)) + "Dog Familiar");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "50% chance to do 25% more damage ");
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("FoxFamiliar")){
            ItemStack Item = new ItemStack(Material.FOX_SPAWN_EGG, 1);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(227, 158, 48)) + "Fox Familiar");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "Faster movement speed ");
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("BunnyFamiliar")){
            ItemStack Item = new ItemStack(Material.RABBIT_SPAWN_EGG, 1);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(227, 158, 48)) + "Bunny Familiar");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "Drops a random food item");
            Lore.add(ChatColor.RED + "" + ChatColor.ITALIC + "periodically ");
            Lore.add(ChatColor.of(new Color(242, 80, 145)) +                   "<==============================>");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBDefence")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Defense:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Gives nearby players resistance");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("iItem")){
            ItemStack Item = new ItemStack(Material.ITEM_FRAME);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Invisible Item Frame");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Turns into an Invisible Item Frame");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "after being used on a lodestone");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("RegenDust")){
            ItemStack Item = new ItemStack(Material.REDSTONE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(242, 15, 64)) + "Regen Dust");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(214, 51, 114)) + "" + ChatColor.ITALIC + "Get Regeneration II");
            Lore.add(ChatColor.of(new Color(214, 51, 114)) + "" + ChatColor.ITALIC + "When You Join");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("AlcController")){
            ItemStack Item = new ItemStack(Material.IRON_NUGGET);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(121, 163, 219)) + "Alchemy Controller");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(161, 209, 237)) + "" + ChatColor.ITALIC + "Used with Alchemy");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ZombieEssence")){
            ItemStack Item = new ItemStack(Material.ROTTEN_FLESH);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(212, 108, 17)) + "Zombie Essence");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_GRAY + "" + ChatColor.ITALIC + "Magical form of Rotten Flesh");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("AlchemyDust")){
            ItemStack Item = new ItemStack(Material.BLAZE_POWDER);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(252, 161, 3)) + "Alchemy Dust");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(138, 94, 18)) + "" + ChatColor.ITALIC + "Substance used for Advanced Alchemy");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("AlchemyBlock")){
            ItemStack Item = new ItemStack(Material.MAGMA_BLOCK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(252, 161, 3)) + "Alchemy Block");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(138, 94, 18)) + "" + ChatColor.ITALIC + "Substance used for Ritual Alchemy");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("BeastPotion")){
            ItemStack Item = new ItemStack(Material.POTION);
            PotionMeta Meta = (PotionMeta) Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(0, 0, 0)) + "" + ChatColor.BOLD + "Beast Potion");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(68, 71, 69)) + "" + ChatColor.ITALIC + "Become Strong");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.DAMAGE_RESISTANCE, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.REGENERATION, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.ABSORPTION, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.GLOWING, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.FAST_DIGGING, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 1800, 4), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.CONFUSION, 1800, 4), true);
            Meta.setColor(org.bukkit.Color.BLACK);
            Item.setItemMeta(Meta);
            return Item;
        } else if (s.equalsIgnoreCase("HotCocoa")){
            ItemStack Item = new ItemStack(Material.POTION);
            PotionMeta Meta = (PotionMeta) Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.of(new Color(105, 62, 10)) + "" + ChatColor.BOLD + "Hot Cocoa");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.of(new Color(130, 94, 49)) + "" + ChatColor.ITALIC + "Soothing Beverage in the Winter");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.SPEED, 3600, 0), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 3600, 0), true);
            Meta.addCustomEffect(new PotionEffect(PotionEffectType.ABSORPTION, 3600, 0), true);
            Meta.setColor(org.bukkit.Color.fromRGB(105, 62, 10));
            Item.setItemMeta(Meta);
            return Item;
        } else if (s.equalsIgnoreCase("SBDarkCurse")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Dark Curse:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Damages a player periodically");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Heavy Drain on Mana");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBShadowWandering")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Shadow Wandering:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Travel almost completely invisible");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "with just your shadow showing at the");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "expense of mana");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ZyniumHelmet")){
            ItemStack Item = new ItemStack(Material.NETHERITE_HELMET);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Zynium Helmet");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Armor supported by");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "the Zynium Client");
            Lore.add("");
            Meta.setLore(Lore);
            AttributeModifier modifier = new AttributeModifier(UUID.randomUUID(), "generic.attack_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_ATTACK_SPEED, modifier);
            AttributeModifier modifier2 = new AttributeModifier(UUID.randomUUID(), "generic.movement_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_MOVEMENT_SPEED, modifier2);
            Meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 15);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 15);
            Item.addUnsafeEnchantment(Enchantment.MENDING, 1);
            Item.addUnsafeEnchantment(Enchantment.WATER_WORKER, 7);
            Item.addUnsafeEnchantment(Enchantment.OXYGEN, 7);
            return Item;
        } else if (s.equalsIgnoreCase("ZyniumChestplate")){
            ItemStack Item = new ItemStack(Material.NETHERITE_CHESTPLATE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Zynium Chestplate");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Armor supported by");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "the Zynium Client");
            Lore.add("");
            Meta.setLore(Lore);
            AttributeModifier modifier = new AttributeModifier(UUID.randomUUID(), "generic.attack_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_ATTACK_SPEED, modifier);
            AttributeModifier modifier2 = new AttributeModifier(UUID.randomUUID(), "generic.movement_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_MOVEMENT_SPEED, modifier2);
            Meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 15);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 15);
            Item.addUnsafeEnchantment(Enchantment.MENDING, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ZyniumLeggings")){
            ItemStack Item = new ItemStack(Material.NETHERITE_LEGGINGS);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Zynium Leggings");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Armor supported by");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "the Zynium Client");
            Lore.add("");
            Meta.setLore(Lore);
            AttributeModifier modifier = new AttributeModifier(UUID.randomUUID(), "generic.attack_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_ATTACK_SPEED, modifier);
            AttributeModifier modifier2 = new AttributeModifier(UUID.randomUUID(), "generic.movement_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_MOVEMENT_SPEED, modifier2);
            Meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 15);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 15);
            Item.addUnsafeEnchantment(Enchantment.MENDING, 1);
            return Item;
        } else if (s.equalsIgnoreCase("ZyniumBoots")){
            ItemStack Item = new ItemStack(Material.NETHERITE_BOOTS);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Zynium Boots");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Armor supported by");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "the Zynium Client");
            Lore.add("");
            Meta.setLore(Lore);
            AttributeModifier modifier = new AttributeModifier(UUID.randomUUID(), "generic.attack_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_ATTACK_SPEED, modifier);
            AttributeModifier modifier2 = new AttributeModifier(UUID.randomUUID(), "generic.movement_speed", 0.006, AttributeModifier.Operation.ADD_NUMBER);
            Meta.addAttributeModifier(Attribute.GENERIC_MOVEMENT_SPEED, modifier2);
            Meta.addItemFlags(ItemFlag.HIDE_ATTRIBUTES);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 15);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 15);
            Item.addUnsafeEnchantment(Enchantment.MENDING, 1);
            Item.addUnsafeEnchantment(Enchantment.DEPTH_STRIDER, 7);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_FALL, 7);
            return Item;
        } else if (s.equalsIgnoreCase("ZyniumFragment")){
            ItemStack Item = new ItemStack(Material.NETHERITE_INGOT);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Zynium Fragment");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Useless on its own, but");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "powerful when crafted into armor");
            Lore.add(ChatColor.BLUE + "" + ChatColor.ITALIC + "Supported by the Zynium Client");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBAbsorb")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Absorb:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Absorb almost any Living Entity");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "in front of you. Excludes players");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBFreeze")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Freeze:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Freezes Entities close to you");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("WardenWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "" + ChatColor.BOLD + "W" + ChatColor.MAGIC + "a" + ChatColor.RED + ChatColor.BOLD + "rd" + ChatColor.MAGIC + "e" + ChatColor.RED + "" + ChatColor.BOLD + "n W" + ChatColor.MAGIC + "a" + ChatColor.RED + "" + ChatColor.BOLD + "nd");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "An extremely tough wand");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBIronWallAttack")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Iron Wall Attack:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Launches an iron wall,");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "a defensive structure,");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "to body slam your target");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBLifeSteal")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Life Steal:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "After locking on an entity,");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "you can steal 4 of their hearts,");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "and you will be pulled toward them");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("DestructionWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.DARK_RED + "D" + ChatColor.RED + "e" + ChatColor.DARK_RED + "s" + ChatColor.RED + "t" + ChatColor.DARK_RED + "r" + ChatColor.RED + "u" + ChatColor.DARK_RED + "c" + ChatColor.RED + "t" + ChatColor.DARK_RED + "i" + ChatColor.RED + "o" + ChatColor.DARK_RED + "n " + ChatColor.RED + "W" + ChatColor.DARK_RED + "a" + ChatColor.RED + "n" + ChatColor.DARK_RED + "d");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Explosive nature,");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "to be used with extreme caution");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBSmite")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Smite:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Ability to summon lighting");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "with a range of 50 meters");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBFireball")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Fireball:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Ability to launch a fireball");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBTimeBomb")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Time Bomb:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Summon an enhanced end crystal");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "to explode after 20 seconds");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBWither")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Wither:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Dry out any living block near you");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("AquaWand")){
            ItemStack Item = new ItemStack(Material.STICK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.AQUA + "A" + ChatColor.BLUE + "q" + ChatColor.AQUA + "u" + ChatColor.BLUE + "a " + ChatColor.AQUA + "W" + ChatColor.BLUE + "a" + ChatColor.AQUA + "n" + ChatColor.BLUE + "d");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "" + ChatColor.ITALIC + "Thirsty?");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBDrown")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Drown:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Drown your opponent as long");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "as you are not moving");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("SBIceShards")){
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Spell Book");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "Ice Shards:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "Shoot deadly shards of ice");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.DURABILITY, 1);
            return Item;
        } else if (s.equalsIgnoreCase("wardenRemnants")) {
            ItemStack Item = new ItemStack(Material.IRON_BLOCK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(org.bukkit.ChatColor.WHITE + "" + org.bukkit.ChatColor.BOLD + "Warden Remnants");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add(org.bukkit.ChatColor.WHITE + "" + org.bukkit.ChatColor.ITALIC + "Obtained by the Warden");
            Meta.setLore(Lore);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("MonsterNotifier")) {
            ItemStack Item = new ItemStack(Material.CLOCK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.DARK_GREEN + "Monster King Notifier");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "If a Monster King spawns near");
            Lore.add(ChatColor.GREEN + "you with this in your inventory,");
            Lore.add(ChatColor.GREEN + "you will be notified");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("fill")) {
            ItemStack Item = new ItemStack(Material.BLACK_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.BLACK + "");
            Item.setItemMeta(Meta);
            return Item;
        } else if (s.equalsIgnoreCase("fillLime")) {
            ItemStack Item = new ItemStack(Material.LIME_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.BLACK + "");
            Item.setItemMeta(Meta);
            return Item;
        } else if (s.equalsIgnoreCase("arrowBanner")) {
            ItemStack Item = new ItemStack(Material.GRAY_BANNER);
            BannerMeta meta = (BannerMeta) Item.getItemMeta();
            assert meta != null;
            meta.setDisplayName(ChatColor.BLACK + "");
            java.util.List<Pattern> patterns = new ArrayList<>();
            patterns.add(new Pattern(DyeColor.WHITE, PatternType.RHOMBUS_MIDDLE));
            patterns.add(new Pattern(DyeColor.WHITE, PatternType.HALF_VERTICAL));
            patterns.add(new Pattern(DyeColor.GRAY, PatternType.SQUARE_BOTTOM_LEFT));
            patterns.add(new Pattern(DyeColor.GRAY, PatternType.SQUARE_TOP_LEFT));
            patterns.add(new Pattern(DyeColor.GRAY, PatternType.TRIANGLES_BOTTOM));
            patterns.add(new Pattern(DyeColor.GRAY, PatternType.TRIANGLES_TOP));
            patterns.add(new Pattern(DyeColor.GRAY, PatternType.BORDER));
            meta.setPatterns(patterns);
            meta.addItemFlags(ItemFlag.HIDE_POTION_EFFECTS);
            Item.setItemMeta(meta);
            return Item;
        } else if (s.equalsIgnoreCase("potentialPane")) {
            ItemStack Item = new ItemStack(Material.LIGHT_BLUE_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.AQUA + "Potential");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_AQUA + "The path the spell takes towards");
            Lore.add(ChatColor.DARK_AQUA + "the desired activation point");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("aePane")) {
            ItemStack Item = new ItemStack(Material.LIME_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.GREEN + "Area Effect");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_GREEN + "The size and direction ");
            Lore.add(ChatColor.DARK_GREEN + "of the affected area");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("intensityPane")) {
            ItemStack Item = new ItemStack(Material.RED_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Intensity");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_RED + "The main effect of the spell");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("accuracyPane")) {
            ItemStack Item = new ItemStack(Material.MAGENTA_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Accuracy");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_PURPLE + "The amount of influence a player has determining");
            Lore.add(ChatColor.DARK_PURPLE + "the location of the activation point");
            Lore.add(ChatColor.DARK_PURPLE + "Accepts: Iron Ingots, Gold Ingots, Diamonds,");
            Lore.add(ChatColor.DARK_PURPLE + "Netherite Ingots, Netherite Blocks");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("controlPane")) {
            ItemStack Item = new ItemStack(Material.BLUE_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.BLUE + "Control");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.DARK_BLUE + "The ease at which a player");
            Lore.add(ChatColor.DARK_BLUE + "summons magic particles accurately");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("magicDustPane")) {
            ItemStack Item = new ItemStack(Material.YELLOW_STAINED_GLASS_PANE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Magic Dust ");
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GOLD + "Creating spells require Magic Dust");
            Lore.add(ChatColor.GOLD + "Not enough dust will result in");
            Lore.add(ChatColor.GOLD + "a failed combination");
            Lore.add("");
            Meta.setLore(Lore);
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("fireEssence")) {
            ItemStack Item = new ItemStack(Material.BLAZE_POWDER);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.RED + "Fire Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("earthEssence")) {
            ItemStack Item = new ItemStack(Material.RAW_IRON);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.GRAY + "Earth Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("waterEssence")) {
            ItemStack Item = new ItemStack(Material.PRISMARINE_CRYSTALS);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.BLUE + "Water Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("windEssence")) {
            ItemStack Item = new ItemStack(Material.FEATHER);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.WHITE + "Wind Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("electricityEssence")) {
            ItemStack Item = new ItemStack(Material.COPPER_INGOT);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.GOLD + "Electricity Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("iceEssence")) {
            ItemStack Item = new ItemStack(Material.GHAST_TEAR);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.AQUA + "Ice Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("poisonEssence")) {
            ItemStack Item = new ItemStack(Material.FERMENTED_SPIDER_EYE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.DARK_GRAY + "Poison Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("livingEssence")) {
            ItemStack Item = new ItemStack(Material.SCUTE);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.GREEN + "Living Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("spectralEssence")) {
            ItemStack Item = new ItemStack(Material.AMETHYST_SHARD);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.LIGHT_PURPLE + "Spectral Essence");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        } else if (s.equalsIgnoreCase("mysteriousSpell")) {
            ItemStack Item = new ItemStack(Material.ENCHANTED_BOOK);
            ItemMeta Meta = Item.getItemMeta();
            assert Meta != null;
            Meta.setDisplayName(ChatColor.YELLOW + "Mysterious Spell");
            Meta.addItemFlags(ItemFlag.HIDE_ENCHANTS);
            ArrayList<String> Lore = new ArrayList<>();
            Lore.add("");
            Lore.add(ChatColor.GREEN + "" + ChatColor.ITALIC + "??? Spell:");
            Lore.add(ChatColor.DARK_GREEN + "" + ChatColor.ITALIC + "" + ChatColor.MAGIC + "Shit hit the fan");
            Lore.add("");
            Meta.setLore(Lore);
            Item.setItemMeta(Meta);
            Item.addUnsafeEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            return Item;
        }
        return null;
    }

    public boolean isWand(ItemStack itemStack){
        return (itemStack.isSimilar(data("BasicWand")) || itemStack.isSimilar(data("ProsaicWand")) || itemStack.isSimilar(data("ShadowWand")) || itemStack.isSimilar(data("EnhancedWand")) || itemStack.isSimilar(data("WardenWand")) || itemStack.isSimilar(data("DestructionWand")) || itemStack.isSimilar(data("AquaWand")));
    }

    public boolean isEssence(ItemStack itemStack){
        return itemStack.isSimilar(data("fireEssence")) || itemStack.isSimilar(data("earthEssence")) || itemStack.isSimilar(data("waterEssence")) || itemStack.isSimilar(data("windEssence")) || itemStack.isSimilar(data("electricityEssence")) || itemStack.isSimilar(data("iceEssence")) || itemStack.isSimilar(data("poisonEssence")) || itemStack.isSimilar(data("livingEssence")) || itemStack.isSimilar(data("spectralEssence"));
    }

}
